
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module CPU_top(

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// HDMI //////////
	inout 		          		HDMI_I2C_SCL,
	inout 		          		HDMI_I2C_SDA,
	inout 		          		HDMI_I2S,
	inout 		          		HDMI_LRCLK,
	inout 		          		HDMI_MCLK,
	inout 		          		HDMI_SCLK,
	output		          		HDMI_TX_CLK,
	output		          		HDMI_TX_DE,
	output		    [23:0]		HDMI_TX_D,
	output		          		HDMI_TX_HS,
	input 		          		HDMI_TX_INT,
	output		          		HDMI_TX_VS,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// GPIO_0, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_1
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

// =============== CLOCK =============== 
wire clk = ~KEY[0];

//=======================================================
//  Structural coding
//=======================================================

CPU CPU(
    .clk(clk),
    .reset(SW[0]),
    .DATA_IN_BUS(GPIO_1[7:0]),
    .DATA_OUT_BUS(GPIO_0[7:0]),
    .ADDR_OUT_BUS(GPIO_0[17:10]),
    .WRITE_EN(GPIO_0[35]),
    .DEBUG(LED[7:0])
);

endmodule
